import { chromium } from "playwright";
const S = process.argv[2];
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--use-gl=swiftshader", "--enable-webgl", "--ignore-gpu-blocklist"] });
const page = await browser.newPage({ viewport: { width: 1500, height: 1100 } });
const errors = [];
page.on("pageerror", (e) => errors.push("pageerror: " + e.message));
const r = await page.request.post("http://localhost:3000/api/auth/request", { data: { email: "owner1@example.com" } });
const { devLink } = await r.json();
await page.goto(devLink, { waitUntil: "networkidle" });
await page.goto("http://localhost:3000/dashboard", { waitUntil: "networkidle", timeout: 120000 });
await page.waitForTimeout(2500);
await page.screenshot({ path: `${S}/dash.png`, fullPage: true });
await page.goto("http://localhost:3000/", { waitUntil: "networkidle", timeout: 120000 });
await page.waitForTimeout(8000);
await page.screenshot({ path: `${S}/home3.png` });
await page.goto("http://localhost:3000/seasons", { waitUntil: "networkidle", timeout: 120000 });
await page.screenshot({ path: `${S}/seasons.png` });
console.log(errors.join("\n") || "no errors");
await browser.close();
