// Books on display: house booth gets covers on two platforms; another booth buys 2 books in test mode, uploads one, is refused a third.
import { chromium } from "playwright";
import fs from "node:fs";
const out = "/tmp/claude-0/-home-user-corematrix/80df1d3b-37c9-5f70-bd13-ed1efde32587/scratchpad";
const base = "http://localhost:3000";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--use-gl=swiftshader", "--enable-webgl", "--ignore-gpu-blocklist"] });
const ctx = await b.newContext({ viewport: { width: 1280, height: 800 } });
const p = await ctx.newPage();
const art = await ctx.newPage();
const cover = async (name, bg, txt) => { await art.setContent(`<body style="margin:0;width:600px;height:900px;background:${bg};color:#fff;font:900 110px Arial;display:grid;place-items:center;text-align:center">${txt}</body>`); await art.screenshot({ path: `${out}/${name}.png` }); return fs.readFileSync(`${out}/${name}.png`); };
const c1 = await cover("cover1", "#7c3aed", "ISSUE<br>#1"), c2 = await cover("cover2", "#dc2626", "ISSUE<br>#2");
await art.close();
const upload = async (page, boothId, slot, buf) => { let r = await page.request.post(`${base}/api/art/upload`, { multipart: { slot, file: { name: "c.png", mimeType: "image/png", buffer: buf } } }); const j = await r.json(); if (!r.ok) return `upload ${r.status()} ${j.error}`; r = await page.request.post(`${base}/api/booth/${boothId}/art`, { data: { slot, url: j.url } }); const k = await r.json(); return `${r.status()} ${k.error || Object.keys(k.art || {}).filter((x) => x.startsWith("book")).join(",")}`; };
await p.request.post(`${base}/api/auth/password`, { data: { email: "divinitycomicsinc@gmail.com", password: "DFLKji4i9ksl" } });
const h = await (await p.request.get(`${base}/api/booth/442`)).json(); console.log("house bookSlots", h.booth.bookSlots);
console.log("house book:0", await upload(p, 442, "book:0", c1)); console.log("house book:5", await upload(p, 442, "book:5", c2));
const q = await ctx.newPage();
await q.request.post(`${base}/api/auth/password`, { data: { email: "banner-smoke@example.com", password: "smoke-test-pass-1" } });
const mine = await (await q.request.get(`${base}/api/me`)).json(); const bid = mine.booths[0]?.id; console.log("buyer booth", bid);
console.log("book:0 before buying", await upload(q, bid, "book:0", c1));
let r = await q.request.post(`${base}/api/checkout`, { data: { kind: "book", boothId: bid, qty: 2 } }); let j = await r.json(); console.log("book checkout", r.status(), j.txId ? "ok" : j);
await q.goto(j.url, { waitUntil: "networkidle", timeout: 120000 }); await q.locator("text=Loading secure checkout").waitFor({ state: "hidden", timeout: 20000 }).catch(() => {}); await q.waitForTimeout(800); const f = q.frames().find((f) => f.url().includes("/checkout/simulate")); await f.click('button:has-text("Pay now")'); await q.waitForTimeout(3500);
const d = await (await q.request.get(`${base}/api/booth/${bid}`)).json(); console.log("bookSlots after", d.booth.bookSlots, "value", d.booth.valueCents, "history", d.history.map((x) => x.kind).join(","));
console.log("book:1", await upload(q, bid, "book:1", c2)); console.log("book:2 (not paid)", await upload(q, bid, "book:2", c1));
await q.goto(`${base}/app/dashboard?booth=${bid}`, { waitUntil: "networkidle" }); await q.waitForTimeout(800);
const sec = q.locator("text=Books on display"); await sec.scrollIntoViewIfNeeded(); await q.screenshot({ path: `${out}/dash-books.png` });
await p.goto(`${base}/app?clean=1&cam=20,6,-74,-5,3.2,-72`, { waitUntil: "load", timeout: 180000 }); await p.waitForTimeout(6000);
await p.screenshot({ path: `${out}/books.png` });
await b.close();
